name: RetroArch AppImage Nightly Build

on:
  schedule:
  - cron: "0 5 * * *"
  watch:
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  job1:
    name: Build RetroArch AppImage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch dependencies
      run: sudo apt-get update ; sudo apt-get install libasound2-dev libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libc6-dev libdbus-1-dev libdrm-dev libegl1-mesa-dev libfreetype6-dev libgbm-dev libglm-dev libjack-jackd2-dev libopenal-dev libpulse-dev libsdl2-dev libswscale-dev libudev-dev libusb-1.0-0-dev libv4l-dev libvulkan-dev libxinerama-dev libxml2-dev libxv-dev libxxf86vm-dev pkg-config python3-dev qt5-default qtbase5-dev wayland-protocols x11proto-xext-dev zlib1g-dev
    - name: Build and bundle RetroArch
      run: ./retroarch-appimage-recipe.sh
    - name: Upload RetroArch AppImage
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: RetroArch-Nightly.AppImage
        tag: Nightlies
        asset_name: RetroArch-Nightly.AppImage
        overwrite: true

  job2:
    name: Fetch and bundle assets
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Fetch dependencies
      run: sudo apt-get update ; sudo apt-get install p7zip-full
    - name: Make dirs
      run: mkdir mkdir assets cores shaders database cheats
    - name: Fetch assets
      run: cd assets && wget https://buildbot.libretro.com/assets/frontend/assets.zip && unzip assets.zip && rm assets.zip
    - name: Fetch overlays
      run: git clone https://github.com/libretro/common-overlays.git && mv common-overlays overlays
    - name: Fetch autoconfigs
      run: git clone https://github.com/libretro/retroarch-joypad-autoconfig.git && mv retroarch-joypad-autoconfig autoconfig
    - name: Fetch shaders
      run: cd shaders && git clone https://github.com/libretro/glsl-shaders.git && git clone https://github.com/libretro/slang-shaders.git
    - name: Fetch databases
      run: cd database && wget https://buildbot.libretro.com/assets/frontend/database-rdb.zip && unzip database-rdb.zip && rm database-rdb.zip
    - name: Fetch cheats
      run: cd cheats && wget https://buildbot.libretro.com/assets/frontend/cheats.zip && unzip cheats.zip && rm cheats.zip
    - name: Fetch core info
      run: cd cores && wget https://buildbot.libretro.com/assets/frontend/info.zip && unzip info.zip && rm info.zip
    - name: Zip it up!
      run: 7z a -x'!retroarch-appimage-recipe.sh' -x'!README.md' -x'!LICENSE' RetroArch-Nightly.AppImage.config.7z *
    - name: Upload assets bundle
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: RetroArch-Nightly.AppImage.config.7z
        tag: Nightlies
        asset_name: RetroArch-Nightly.AppImage.config.7z
        overwrite: true
